{
 "title": "System stats per host",
 "tags": [ "telegraf" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host" }
  ]
 },
 "panels": [
  { "title": "Load/CPU/Memory/Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}",
     "legendFormat": "{{host}} 1min"
    },
    {
     "expr": "system_load5{host=~\"$host\"}",
     "legendFormat": "{{host}} 5min"
    },
    {
     "expr": "system_load15{host=~\"$host\"}",
     "legendFormat": "{{host}} 15min"
    }
   ]
  },
  {
   "title": "Mem stats",
   "type": "graph",
   "gridPos": { "h": 18, "w": 11, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_dirty{host=~\"$host\"}"
    },
    {
     "expr": "mem_shared{host=~\"$host\"}"
    },
    {
     "expr": "mem_active{host=~\"$host\"}"
    },
    {
     "expr": "mem_buffered{host=~\"$host\"}"
    },
    {
     "expr": "mem_available{host=~\"$host\"}"
    },
    {
     "expr": "mem_cached{host=~\"$host\"}"
    },
    {
     "expr": "mem_vmalloc_used{host=~\"$host\"}"
    },
    {
     "expr": "mem_total{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mem_used{host=~\"$host\"}",
     "legendFormat": "{{host}} Used"
    },
    {
     "expr": "mem_buffered{host=~\"$host\"} + mem_cached{host=~\"$host\"}",
     "legendFormat": "{{host}} Buffers+cache"
    },
    {
     "expr": "mem_free{host=~\"$host\"}",
     "legendFormat": "{{host}} Free"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\",host=~\"$host\"}",
     "legendFormat": "{{host}} user"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\", host=~\"$host\"}",
     "legendFormat": "{{host}} system"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\",host=~\"$host\"}",
     "legendFormat": "{{host}} iowait"
    },
    {
     "expr": "cpu_usage_nice{cpu=\"cpu-total\",host=~\"$host\"}",
     "legendFormat": "{{host}} nice"
    },
    {
     "expr": "cpu_usage_softirq{cpu=\"cpu-total\",host=~\"$host\"}",
     "legendFormat": "{{host}} softirq"
    },
    {
     "expr": "cpu_usage_irq{cpu=\"cpu-total\",host=~\"$host\"}",
     "legendFormat": "{{host}} irq"
    },
    {
     "expr": "cpu_usage_guest{cpu=\"cpu-total\", host=~\"$host\"}",
     "legendFormat": "{{host}} guest"
    },
    {
     "expr": "cpu_usage_guest_nice{cpu=\"cpu-total\", host=~\"$host\"}",
     "legendFormat": "{{host}} guest_nice"
    },
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\", host=~\"$host\"}",
     "legendFormat": "{{host}} idle"
    }
   ]
  },
  {
   "title": "CPU steal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_steal{cpu=\"cpu-total\",host=~\"$host\"}",
     "legendFormat": "{{host}} steal"
    }
   ]
  },
  {
   "title": "Swap used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "swap_used_percent{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Swap in/out throuput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(swap_in{host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} In"
    },
    {
     "expr": "rate(swap_out{host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} Out"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  { "title": "Disk performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "IOPS Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_reads{name=~\"nvme.*|sd.*|xv.*|vd.*|dasd.*|bcache.*\",name!~\"nvme.*p[0-9]+$|.*sd.*[0-9]$|xv.*[0-9]$|vd.*[0-9]$|dasd.*[0-9]$\",host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} {{name}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_writes{name=~\"nvme.*|sd.*|xv.*|vd.*|dasd.*|bcache.*\",name!~\"nvme.*p[0-9]+$|.*sd.*[0-9]$|xv.*[0-9]$|vd.*[0-9]$|dasd.*[0-9]$\",host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} {{name}}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_read_bytes{name=~\"nvme.*|sd.*|xv.*|vd.*|dasd.*|bcache.*|md0\",name!~\"nvme.*p[0-9]+$|.*sd.*[0-9]$|xv.*[0-9]$|vd.*[0-9]$|dasd.*[0-9]$\",host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} {{name}}"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_write_bytes{name=~\"nvme.*|sd.*|xv.*|vd.*|dasd.*|bcache.*|md0\",name!~\"nvme.*p[0-9]+$|.*sd.*[0-9]$|xv.*[0-9]$|vd.*[0-9]$|dasd.*[0-9]$\",host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} {{name}}"
    }
   ]
  },
  {
   "title": "IO wait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(diskio_io_time{name=~\"nvme.*|sd.*|xv.*|vd.*|dasd.*|bcache.*|md0\",name!~\"nvme.*p[0-9]+$|.*sd.*[0-9]$|xv.*[0-9]$|vd.*[0-9]$|dasd.*[0-9]$\",host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} {{name}}"
    }
   ]
  },
  { "title": "Disk space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Disk space  (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "disk_free{host=~\"$host\"}",
     "legendFormat": "{{host}} \"{{path}}\" Free"
    },
    {
     "expr": "disk_used{host=~\"$host\"}",
     "legendFormat": "{{host}} \"{{path}}\" Used"
    }
   ]
  },
  {
   "title": "Disk space % used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used{host=~\"$host\"} / disk_total{host=~\"$host\"} * 100",
     "legendFormat": "{{host}} \"{{path}}\""
    }
   ]
  },
  {
   "title": "Inodes % used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "repeat": "mountpoint",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_inodes_used{host=~\"$host\"} /  disk_inodes_total{host=~\"$host\"} * 100",
     "legendFormat": "{{host}} \"{{path}}\""
    }
   ]
  },
  { "title": "Kernel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_interrupts{host=~\"$host\"}[1m])"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_processes_forked{host=~\"$host\"}[1m])"
    }
   ]
  },
  {
   "title": "Available entropy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_entropy_avail{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Kernel context switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_context_switches{host=~\"$host\"}[1m])"
    }
   ]
  }
 ]
}